name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: youruser/cap:latest

      - name: Deploy to Dedicated Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull youruser/cap:latest
            docker stop react-container || true
            docker rm react-container || true
            docker run -d --name react-container \
              -p 80:80 \
              -v certbot-etc:/etc/letsencrypt \
              -v certbot-www:/var/www/certbot \
              -v /opt/certbot-nginx/nginx-temp.conf:/etc/nginx/conf.d/default.conf:ro \
              nginx
