name: Build & Deploy Frontend

on:
  push:
    branches: [main]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: myaccess2021/cap:latest

      - name: Deploy to Dedicated Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull myaccess2021/cap:latest
            docker stop react-container2 || true
            docker rm react-container2 || true
            docker run -d \
              --name react-container2 \
              --network cap-network \
              -p 80:80 \
              myaccess2021/cap:latest
